'use strict';

(function() {
  var HEIGTH_PIN = 70;
  var HALF_WIDTH_PIN = 25;

  var CARDS_LENGTH = 8;

  var CARDS_PRICES_MIN = 1;
  var CARDS_PRICES_MAX = 10;

  var CARDS_ROOMS_MIN = 1;
  var CARDS_ROOMS_MAX = 4;

  var CARDS_GUESTS_MIN = 1;
  var CARDS_GUESTS_MAX = 5;

  var CARDS_LOCATION_X_MIN = 25;
  var CARDS_LOCATION_Y_MIN = 130;
  var CARDS_LOCATION_Y_MAX = 630;

  var POINT_HEIGHT = 22;
  var POINT_WIDTH = 10;

  var TITLE_MIN_LENGTH = 30;
  var TITLE_MAX_LENGTH = 100;

  var MAX_PRICE = 1000000;

  window.constants = {
    HEIGTH_PIN: HEIGTH_PIN,
    HALF_WIDTH_PIN: HALF_WIDTH_PIN,
    CARDS_LENGTH: CARDS_LENGTH,
    CARDS_PRICES_MIN: CARDS_PRICES_MIN,
    CARDS_PRICES_MAX: CARDS_PRICES_MAX,
    CARDS_ROOMS_MIN: CARDS_ROOMS_MIN,
    CARDS_ROOMS_MAX: CARDS_ROOMS_MAX,
    CARDS_GUESTS_MIN: CARDS_GUESTS_MIN,
    CARDS_GUESTS_MAX: CARDS_GUESTS_MAX,
    CARDS_LOCATION_X_MIN: CARDS_LOCATION_X_MIN,
    CARDS_LOCATION_Y_MIN: CARDS_LOCATION_Y_MIN,
    CARDS_LOCATION_Y_MAX: CARDS_LOCATION_Y_MAX,
    POINT_WIDTH: POINT_WIDTH,
    POINT_HEIGHT: POINT_HEIGHT,
    TITLE_MIN_LENGTH: TITLE_MIN_LENGTH,
    TITLE_MAX_LENGTH: TITLE_MAX_LENGTH,
    MAX_PRICE: MAX_PRICE
  }
})();
